<aside class="main-sidebar">
    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">
      <!-- Sidebar user panel -->
      <div class="user-panel">
        <div class="pull-left image">
          <img src="./dist/img/user2-160x160.jpg" class="img-circle" alt="User Image">
        </div>
        <div class="pull-left info">
          <p>Alexander Pierce</p>
          <a href="#"><i class="fa fa-circle text-success"></i> Online</a>
        </div>
      </div>
      <!-- search form -->
      <form action="#" method="get" class="sidebar-form">
        <div class="input-group">
          <input type="text" name="q" class="form-control" placeholder="Search...">
              <span class="input-group-btn">
                <button type="submit" name="search" id="search-btn" class="btn btn-flat"><i class="fa fa-search"></i>
                </button>
              </span>
        </div>
      </form>
      <!-- /.search form -->
      <!-- sidebar menu: : style can be found in sidebar.less -->
      <ul class="sidebar-menu">
        <li class="header">MAIN NAVIGATION</li>
        <li class="active treeview">
          <a href="qltk.php">
            <i class="fa fa-dashboard"></i> <span>Quản lý tài khoản</span>
          </a>
        </li>
        <li class="treeview">
          <a href="qlbs.php">
            <i class="fa fa-files-o"></i>
            <span>Quản lý bác sĩ</span>
          </a>
        </li>
        <li>
          <a href="qlbv.php">
            <i class="fa fa-th"></i> <span>Quản lý bệnh viện</span>
          </a>
        </li>
        <li class="treeview">
          <a href="qlk.php">
            <i class="fa fa-pie-chart"></i>
            <span>Quản lý khoa</span>
          </a>
        </li>
        <li class="treeview">
          <a href="qltc.php">
            <i class="fa fa-laptop"></i>
            <span>Quản lý triệu chứng</span>
          </a>
        </li>
      </ul>
    </section>
    <!-- /.sidebar -->
  </aside>